//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iteration_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnalysisDBEntities1 : DbContext
    {
        public AnalysisDBEntities1()
            : base("name=AnalysisDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeGroup> AgeGroup { get; set; }
        public virtual DbSet<English_Profeciency> English_Profeciency { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Highest_education> Highest_education { get; set; }
        public virtual DbSet<Prediction> Prediction { get; set; }
    }
}
